docker compose downversion: '3.8'

x-airflow-common: &airflow-common
  build: .
  image: taller_etl_master-airflow:latest
  env_file: .env

  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth

    # FIX LOGS
    AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080

    # DB Warehouse
    AIRFLOW_CONN_POSTGRES_WAREHOUSE_CONN: postgresql://${DB_USER}:${DB_PASS}@postgres_warehouse:5432/${DB_NAME}

    # MinIO (S3)
    AWS_ACCESS_KEY_ID: minio
    AWS_SECRET_ACCESS_KEY: minio123
    S3_ENDPOINT_URL: http://minio:9000
    RAW_BUCKET: raw-zone

    # Variables API
    API_KEY: ${API_KEY}
    API_BASE_URL: ${API_BASE_URL}

    # DB vars
    DB_USER: ${DB_USER}
    DB_PASS: ${DB_PASS}
    DB_HOST: postgres_warehouse
    DB_NAME: ${DB_NAME}
    DB_PORT: 5432

    SALT_PII: ${SALT_PII}

    GX_NO_USAGE_STATS: 'true'
    DBT_PROFILES_DIR: /opt/airflow/dbt

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./dbt:/opt/airflow/dbt
    - ./gx:/opt/airflow/gx
    - ./scripts:/opt/airflow/scripts
    - ./data_lake:/opt/airflow/data_lake
    - ./init_db:/docker-entrypoint-initdb.d
    - ./config:/opt/airflow/config

  user: "${AIRFLOW_UID:-50000}:0"

services:

  # Postgres Airflow Metadata
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  # Postgres Warehouse
  postgres_warehouse:
    image: postgres:13
    container_name: postgres_warehouse
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - warehouse-db-volume:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio-lakehouse
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Airflow Init
  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow

  # Webserver
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  # Scheduler
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres-db-volume:
  warehouse-db-volume:
  minio_data: